- name: prompt from variables
  hosts: localhost
  var_prompt:
  - name: USERNAME
    prmopt: enter user name
    private: no
  - name: PASSWORD
    prmopt: enter password
    private: yes
  


  tasks:

   - name: print username and password
     ansible.builtin.debug:
      msg: "username is {{USERNAME}} and password is {{PASSWORD}}"