- name: prompt from variables
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: enter username
    private: no
  - name: PASSWORD
    prompt: enter password
    private: yes

  tasks:

   - name: print username and password
     ansible.builtin.debug:
      msg: "username is {{USERNAME}} and password is {{PASSWORD}}"