- name: prompt from variables
  hosts: localhost
  var_prompt:
   - name: USERNAME
     prompt: enter username
     private: yes
   - name: PASSWORD
     prompt: enter password
     private: no

  tasks:

   - name: print username and password
     ansible.builtin.debug:
      msg: "username is {{USERNAME}} and password is {{PASSWORD}}"