- name: variables from inventory
  hosts: localhost  

  tasks:
    - name: print variables from inventory
      ansible.builtin.debug:
       msg: "am learing {{course}} from {{trainer}} and total duration is {{duration}}"