- name: Data-Types
  hosts: localhost
  vars:
    courses: DevOps with AWS
    Tools:
    - linux
    - shell
    - ansible
    Experience:
      Devops: 3
      AWS: 2
      Docker: 1
    RealTimeExperince: yes
  tasks:
  - name: print courses 
    ansible.builtin.debug:
     msg: "course: {{courses}} tools covered {{Tools}} with experience {{Experience}} and have real-time experinece {{RealTimeExperince}} "