- name: Conditions using filters
  hosts: localhost
  vars_prompt:
  - name: NUMBER
    prompt: print number
    private: no
  tasks:
  - name: number is less than 10
    ansbile.builtin.debug:
     msg: "{{NUMBER}} is less than 10"
    when: NUMBER < 10
