- name: Conditions using filters
  hosts: localhost
  vars_prompt:
    - name: NUMBER
      prompt: print value 
      private: no
  tasks:
  - name: print the value
    ansible.builtin.debug:
     msg: "print Number {{NUMBER}}"