- name: conditions using filter
  hosts: localhost
  vars_prompt:
  - name: NUMBER
    prompt: print number
    private: no

  tasks:
  - name: number is less than 10
    ansible.builtin.debug:
     msg: "{{NUMBER}} is than 10"
    when: NUMBER < 10