- name: Conditions using filters
  hosts: localhost
  vars_prompt:
    - name: NUMBER
      prompt: print value 
      private: no
  tasks:
  - name: number is less than 10
    ansible.builtin.debug:
     msg: "{{NUMBER}} is less than 10"
    while: NUMBER < 10
    
  - name: number is greater than 10  
    ansible.builtin.debug:
     msg: "{{NUMBER}} is greater than 10"
    while: NUMBER >= 10