- name: conditions using filter
  hosts: localhost
  vars_prompt:
  - name: NUMBER
    prompt: print number
    private: no

  tasks:
  - name: print number
    ansible.builtin.debug:
     msg: "NUMBER"