- name: print unique numbers
  hosts: localhost
  vars:
   - numbers: [1, 3, 4, 4, 5, 3, 5, 6, 7]
  tasks:
  - name: remove dupilcates
    ansible.builtin.debug:
     msg: "{{numbers | unique}}"

- name: print Min and Max ages  
  hosts: localhost
  vars:
   - age: [23, 45, 56, 30, 22]
  tasks:
  - name: max age
    ansible.builtin.debug:
     msg: "Minimum age is: {{age | min}}"
  - name: min age
    ansible.builtin.debug:
     msg: "Maximum ages is: {{age | max}}"

- name: convert directory to items
  hosts: localhost  
  vars:
   - my_dict: 
      course: Devops  
      Trainer: shiva
      Duration: 120hrs
  tasks:
  - name: before converting 
    ansible.builtin.debug:
     msg: "Before converting {{ my_dict }}"
  - name: after converting 
    ansible.builtin.debug:
     msg: "Before converting {{ my_dict | dict2items }}"
  
    

