- name: filters
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"  
  tasks:
  - name: print courses
    ansible.builtin.debug:
     msg: "{{course | default('DevOps')}}"

  - name: UPPERCASE
    ansible.builtin.debug:
     msg: "{{ greeting | upper }}"
  - name: LOWERCASE
    ansible.builtin.debug:
     msg: "{{ greeting | lower }}"
