- name: filters
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"  
  tasks:
  - name: print courses
    ansible.builtin.debug:
     msg: "{{course | default('DevOps')}}"

  - name: UPPERCASE
    ansible.builtin.debug:
     msg: "{{ greeting | upper }}"
  - name: LOWERCASE
    ansible.builtin.debug:
     msg: "{{ greeting | lower }}"
---
- name: print unique numbers
  hosts: localhost
  numbers: [1, 3, 4, 5, 5, 4, 6, 7]
  taks:
   - name: remove duplicates
     ansible.builtin.debug:
      msg: "{{numbers | unique }}"