- name: variables from files
  hosts: localhost
  vars_files:
  - vars.yml
  tasks:
   - name: print vaiables from files
     ansilbe.builtin.debug:
      msg: "am learning {{Course}} form {{Trainer}} in {{Duration}}"