- name: prompt from variables
  hosts: localhost
  vars_prompt:
   - name: USERNAME
     prompt: please enter your user name 
     private: no
   - name: PASSWORD 
     prompt: please enter password 
     private: yes

  tasks:

   - name: print username and password
     ansible.builtin.debug:
      msg: "username is {{USERNAME}} and password is {{PASSWORD}}"