- name: variables
  hosts: localhost  
  vars:
    courses: "ansible"
    trainer: "devops"
    duration: "12hrs"
  tasks:
  - name: print info
    ansible.builtin.debug:
     msg: "am learing {{courses}} from {{trainer}} in {{duration}}"  